#!/usr/bin/env bash
# Takes parameters from command line and uses scp for copying a file to a host by using ssh

param=3
if [ "$#" -lt "$param" ] 
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 0
fi

if [ "$4" ] 
then
  scp -i "$4" -o "StrictHostKeyChecking no" "$1" "$3"'@'"$2":~/
else
  scp -o "StrictHostKeyChecking no" "$1" "$3"'@'"$2":~/
fi
