#!/usr/bin/env bash
# Configures an ubuntu server to have nginx installed and listening in port 80, with returning a string on curl

apt-get update
apt-get -y install nginx
chown -R 777 /var/www/html
echo "Holberton School" > /var/www/html/index.html
service nginx reload
