#!/usr/bin/env bash
# Configures an ubuntu server to have nginx installed and listening in port 80, with returning a string on curl
# and configure the location /redirect_me to have a redirection and custom error page return on 404 state

sudo apt-get -y install nginx
sudo chown -R ubuntu:ubuntu /var/www/
sudo mkdir -P /var/www/sherre-holbertonschool.tech/html
sudo printf "Ceci n\'est pas une page\n" > /var/www/sherre-holbertonschool.tech/html/404.html
echo "Holberton School" > /var/www/sherre-holbertonschool.tech/html/index.html
sudo chown -R ubuntu:ubuntu /etc/nginx/
printf "server {\n\tlisten 80;\n\tlisten [::]:80;\n\tserver_name sherre-holbertonschool.tech www.sherre-holbertonschool.tech 34.74.191.132;\n\troot /var/www/sherre-holbertonschool.tech/html;\n\tindex index.html;\n\terror_page 404 /404.html;\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}\n\tlocation /redirect_me {\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n}\n" > /etc/nginx/sites-available/holbertonschool
sudo cp /etc/nginx/sites-available/holbertonschool /etc/nginx/sites-enabled/holbertonschool
sudo systemctl start nginx
