#!/usr/bin/env bash
# Configures an ubuntu server to have nginx installed and listening in port 80, with returning a string on curl
# and configure the location /redirect_me to have a redirection
# configures 404 page return

apt-get update
apt-get -y install nginx
service nginx start
mkdir -p /var/www/html
printf "Ceci n'est pas une page\n" > /var/www/html/404.html
chown -R 777 /var/www/html
echo "Holberton School" > /var/www/html/index.html
printf "server {\n\tlisten 80;\n\tlisten [::]:80;\n\tserver_name _;\n\troot /var/www/html;\n\tindex index.html;\n\terror_page 404 /404.html;\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}\n\tlocation /redirect_me {\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n}\n" > /etc/nginx/sites-available/default
service nginx reload
