#!/usr/bin/env bash
# Debugging of a web server not running on curl 0:80
sed -i "s/\tlisten 80 default_server;/\tlisten 80;/g" /etc/nginx/sites-available/default
sed -i "/ipv6only=on;/d" /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
