#!/usr/bin/env bash
# Debugging of a web server not running on curl 0:80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
