#!/usr/bin/env bash
# Displays "Holberton School" 10 times using while and "hi" in line 9th
i=1
while [ "$i" -le 10 ]; do
    echo "Holberton School";
    if [ "$i" -eq 9 ]; then
        echo "Hi"
    fi
    i=$((i + 1))
done
