#!/usr/bin/env bash
# Displays "Holberton School" 10 times using while and
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
i=1
while [ "$i" -le 10 ]; do
    if [ "$i" -eq 4 ]; then
        echo "bad luck"
    elif [ "$i" -eq 8 ]; then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    i=$((i + 1))
done
