#!/usr/bin/env bash
# Displays "Holberton School" 10 times using while and
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
i=1
while [ "$i" -le 20 ]; do
    echo "$i"
    case $i in
        4)
          echo "bad luck from China"
          ;;
        9)
          echo "bad luck from Japan"
          ;;
        17)
          echo "bad luck from Italy"
          ;;
    esac
    i=$((i + 1))
done
