#!/usr/bin/env bash
# Displays 12 hours and 59 minutes using nested while loops
i=0
j=1
while [ "$i" -le 12 ]; do
    echo "Hour: $i"
    while [ "$j" -le 59 ]; do
        echo "$j"
        j=$((j + 1))
    done
    j=1
    i=$((i + 1))
done
