#!/usr/bin/env bash
# Displays the information about a file
holbi="./holbertonschool"

if [ -e "$holbi" ]; then
    echo "holbertonschool file exists"
else
    echo "holbertonschool file does not exist"
    exit 1
fi

if [ ! -s "$holbi" ]; then
    echo "holbertonschool file is empty"
else
    echo "holbertonschool file is not empty"
fi


if [ -f "$holbi" ]; then
    echo "holbertonschool is a regular file"
fi


