#!/usr/bin/env bash
# Runs nginx as the less privileged nginx user
echo "nginx ALL=/etc/init.d/nginx start" >> /etc/sudoers
chmod 777  /etc/nginx/nginx.conf
echo "error_log /tmp/error.log;
pid /tmp/nginx.pid;
worker_processes 4;
events {
	worker_connections 1024;
}
http {
	client_body_temp_path /tmp/client_body;
	fastcgi_temp_path /tmp/fastcgi_temp;
	proxy_temp_path /tmp/proxy_temp;
	scgi_temp_path /tmp/scgi_temp;
	uwsgi_temp_path /tmp/uwsgi_temp;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	index index.html index.htm index.php;

	default_type application/octet-stream;

server {
	listen 8080;
	listen [::]:8080 default ipv6only=on;

	root /var/www;

	access_log /tmp/access.log;
	error_log /tmp/error.log;

	location / {
		try_files $uri $uri/ /index.html;
	}
	}
}" > /etc/nginx/nginx.conf
pkill apache2
su nginx -c "/usr/sbin/nginx"
