#!/usr/bin/env bash
# Runs nginx as the less privileged nginx user
echo "nginx ALL=/etc/init.d/nginx start" >> /etc/sudoers
chmod 777  /etc/nginx/nginx.conf
sed -i -e 's@include /etc/nginx/conf\.d/\*\.conf@server {\n\tlisten 8080@' -e "s@include /etc/nginx/sites-enabled/\*@listen [::]:8080 default ipv6only=on@" -e 's@^#}@}@' /etc/nginx/nginx.conf
pkill apache2
su nginx -c "/usr/sbin/nginx"
